- src/chd.c
When building `libchdr` with clang and `C89_BUILD=1` using the RetroArch build system printed these warnings. This PR attempts to correctly fix them, please review to make sure this is correct. I would prefer to make these changes upstream before having libchdr in libretro-common diverge from upstream.
```
libretro-common/formats/libchdr/chd.c:639:12: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
uint8_t *sector = &dest[framenum * CD_FRAME_SIZE];
^
libretro-common/formats/libchdr/chd.c:723:12: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
uint8_t *sector = &dest[framenum * CD_FRAME_SIZE];
^
```
> Fix C89 compiler warnings with clang.

- src/flac.c
- src/huffman.c
The next batch of C89 compatible comments backported from libretro-common. Again there is more to come, but its easier to not do it all at once...
> Backport some C89 compatible comments from libretro-common.

- src/cdrom.c
- src/flac.c
Some C89 build fixes backported from libretro-common and tested using `C89_BUILD=1` with the RetroArch build system.
```
libretro-common/formats/libchdr/flac.c: In function ‘flac_decoder_metadata_callback_static’:
libretro-common/formats/libchdr/flac.c:248:27: error: invalid initializer
flac_decoder fldecoder = (flac_decoder *)(client_data);
^
libretro-common/formats/libchdr/flac.c:248:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
flac_decoder fldecoder = (flac_decoder *)(client_data);
^~~~~~~~~~~~
libretro-common/formats/libchdr/flac.c:249:11: error: invalid type argument of ‘->’ (have ‘flac_decoder {aka struct _flac_decoder}’)
fldecoder->sample_rate = metadata->data.stream_info.sample_rate;
^~
libretro-common/formats/libchdr/flac.c:250:11: …
```
> Backport C89 build fixes from libretro-common.

- src/chd.c
- src/chd.h
Moved the CHD_MAKE_TAG() define to the header file and remove the duplicate entry.
Also used CHD_MAKE_TAG() where appropriate instead of "magic numbers" in the header.
According to the source of MAME I added ``GDROM_OLD_METADATA_TAG`` and changed ``GDROM_TRACK_METADATA_TAG`` to ``'CHGD'`` instead of ``'CHTD'`` (see https://github.com/mamedev/mame/blob/9f1c61b8df566d081e19908e1a1b57a716a1f5b3/src/lib/util/chd.h#L230 for reference).
> Some cleanups and corrections

- src/chd.c
- src/chd.h
It's possible to compress CHDv5 with ``chdman`` using "zlib" as the compression format (not just "cdzl").
The codec is the same as the standard zlib compression.
I also corrected the indentation in the header file.
> Support standard zlib compression

- src/chd.c
> Correctly use the ZLIB codec

- src/chd.c
The implementation of ``put_bigendian_uint32`` and ``put_bigendian_uint24`` is identical and the comments don't match. Therefor fix the former to really put ``uint32``.
> Fix put_bigendian_uint32()

- CMakeLists.txt
`BUILD_SHARED_LIBS` is a standard CMake option. It's expected to either control whether the project is built as a shared or a static library, or (as is the case in libchdr) to control whether a shared library is build in addition to a static one.
> Add support for the standard BUILD_SHARED_LIBS cmake option

- CMakeLists.txt
Needs pkg-config.
This is needed when bundling libchdr in other applications that already use either system provided  FLAC and zlib or bundle their own.
> Add options for using system provided FLAC and zlib libraries

- src/chd.c
- src/chd.h
This is basically a copy paste of https://github.com/libretro/beetle-psx-libretro/commit/ee40afa0ca01f5d501277c64ec9cafcf19539c70. Please note that I don't speak C but I was able to make the needed modifications.
I was able to build and try the beetle psx core against this modified library. As far as testing goes this has been part of beetle psx for 3 years so it should be pretty safe to go with.
> backport chd_precache from libretro beetle psx

- CMakeLists.txt
- pkg-config.pc.in
As libchdr is gaining popularity within the libretro community, it would be nice to be able to install it to the system and use it as a shared lib.
This installs the library, its headers and a pkg-config file as well as sets a version.
You may want to set the version to something other than 0.0 if you go along with this. Also, not sure how many headers are needed but the few libretro cores I've looked at only imported `chd.h`.
> add a pkg-config file and install the shared lib and its headers

- CMakeLists.txt
It looks like the genesis-plus-gx core also needs the cdrom.h header. However there is one difference between their version and yours. In theirs, `CD_TRACK_PADDING` is defined and equal to 4, whereas in yours it is an `extern const`.
I tried defining it when building against the system lib here: https://github.com/alucryd/Genesis-Plus-GX/commit/86fca17227ee1ee629a04126c77805b18cdc7718, while it does build successfully, loading any CHD immediately crashes. I'm probably doing it wrong and will look up how extern const should be used. 
This define is the only obvious difference I spotted by just compiling. It might be something else entirely though I'll try to diff their version and your next week.
> ship the cdrom.h header

- CMakeLists.txt
Recent Linux distributions require position independent code when building shared objects, so it's required to add the `-fPIC` parameter to the compiler flags to make it build. Tested on Arch Linux and Ubuntu 20.04.
> Fix building on Linux

- src/coretypes.h
Fixes #25 by adding a typedef for `ssize_t`. Tested on VS 2019 on W10.
> Fix building on MSVC 2019

- src/chd.c
Fast ZLIB allocator was not freed when the CDFL codec was freed. In my case, it resulted in around 7.7KB data leaked every time a CHD file was opened.
> Fix memory leak in cdfl_codec_free

- CMakeLists.txt
This repairs the ability to install the library after building it.
Of potential note, bitstream.h, flac.h, and huffman.h are in the include directory but are not currently listed for installation. I can correct that if need be.
> Fix include installation

- include/libchdr/chd.h
This allows users to read/access files which have been opened externally by the caller.
> Expose chd_open_file in public API

- CMakeLists.txt
Hi, I'm currently working on a Rust wrapper for libchdr and needed a way to easily find the static libraries for linking.
Would this be an acceptable solution for you, would you prefer doing this in another way or am I maybe missing something and this wouldn't be necessary at all for my use case?
> Make installing static libs possible

- CMakeLists.txt
It messes with any project using libchdr as a submodule
> Only set BUILD_SHARED_LIBS if top level

- CMakeLists.txt
With a M1 Mac Mini, I have this error :
```
CMake Error at external/libchdr/CMakeLists.txt:43 (message):
Unknown system processor: arm64
```
While I could add an extra condition to handle this case, I am wondering if having a cpu arch detection is useful as the variable `CPU_ARCH` looks unused.
> cmake: remove processor type detection

- CMakeLists.txt
Allow to detect system `zlib` without `pkg-config`
> cmake: prefer find_package over pkg_check_modules to find zlib

- CMakeLists.txt
```
src\libchdr_chd.c(1591): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
src\libchdr_chd.c(1785): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
src\libchdr_chd.c(1855): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
src\libchdr_chd.c(1991): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. …
```
> cmake: turn off crt deprecation warnings

- include/dr_libs/dr_flac.h
**Changelog**
v0.12.33 - 2021-12-22
- Fix a bug with seeking when the seek table does not start at PCM frame 0.
v0.12.32 - 2021-12-11
- Fix a warning with Clang.
> dr_flac: Version 0.12.33

- src/libchdr_chd.c
Remove a free() call inherited from the original MAME code which
allocated memory within zlib_codec_init(). It is no longer appropriate
to call here, as the data variable now points to the middle of a
caller-owned allocation.
Fixes #67
> Remove erroneous free() call in zlib_codec_init()

- include/libchdr/chd.h
- src/libchdr_chd.c
Add codec stubs for non-CD LZMA and FLAC compression types.
I was trying to use raw CHDs with some libretro cores and they didn't work.  This is why.
> Add support for reading LZMA and FLAC hunks in non-CD CHDs.

- include/libchdr/chd.h
- include/libchdr/coretypes.h
- src/libchdr_chd.c
This PR implements a virtual file I/O layer that goes between libchdr and stdio.
Users of libchdr can optionally implement their own file I/O functions instead
of using the stdio ones so that they can load files from more sources than
just simple files.
For example, users can create core_file implementations that load files over a
network connection, or from RAM, from an archive, etc.
Another benefit is that in the future users which require platform-specific behavior
will be able to implement it themselves instead of making changes to libchdr.
For the sake of backwards-compatibility, chd_open_file now accepts a FILE* instead of a core_file*.
Users wishing to provide their own I/O function implementations may do so by calling the new
chd_open_core_file function.
> use virtual file i/o API which defaults to a stdio wrapper

- include/dr_libs/dr_flac.h
v0.12.39 - 2022-09-17
- Fix compilation with DJGPP.
- Fix compilation error with Visual Studio 2019 and the ARM build.
- Fix an error with SSE 4.1 detection.
- Add support for disabling wchar_t with DR_WAV_NO_WCHAR.
- Improve compatibility with compilers which lack support for explicit struct packing.
- Improve compatibility with low-end and embedded hardware by reducing the amount of stack
allocation when loading an Ogg encapsulated file.
> dr_flac: Version 0.12.39

- include/libchdr/coretypes.h
- src/libchdr_chd.c
Replace `long` with `INT64`, since `long`'s size can vary depending on build environment (Win64 is 4 bytes, Linux/macOS is 8 bytes).
> Fix fseek offset type.

- src/libchdr_huffman.c
I was able to easily trigger a heap corruption on Windows by forcing repcount to the max value. This can happen with corrupted CHDs and it is very similar to a number of crash reports i received.
Issue #90
> Avoid huffman tree buffer overrun in huffman_import_tree_rle

- deps/lzma-22.01/src/CpuArch.c
The header <sys/auxv.h> does not exist for these systems to retrieve the hardware capabilities
> Declare hardware capabilities for the Nintendo Switch and PlayStation Vita

- src/libchdr_chd.c
The chdv5 raw map and rle tree size are read from the header, which may be incorrect if the chd is corrupted, resulting in a malloc failure if huge
> Check mem alloc failures triggered by invalid chd

- .github/workflows/cmake.yml
This will build these 3 targets
- chdr-static (static library)
- chdr (shared library)
- chdr-benchmark (executable)
using 3 different compilers
- AppleClang 14.0.0 (macos-latest)
- GCC 11.3.0 (ubuntu-latest)
- Visual Studio 17 2022 (windows-latest)
> Add basic GitHub Actions
